// test post at shortest paths

// POST  at http://localhost:8000/shortest-paths

# POST http://127.0.0.1:8000/shortest_path
# Content-Type: application/json

# {
#   "source": 1,
#   "target": 3572
# }

## Get Connected Nodes
GET http://localhost:8000/connected_nodes/1
Accept: application/json

# GET http://localhost:8000/count_nodes